//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupTranGiaTichDiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Redemption
    {
        public int redemption_id { get; set; }
        public Nullable<System.DateTime> redemption_date { get; set; }
        public Nullable<int> reward_id { get; set; }
        public Nullable<int> red_acc_id { get; set; }
        public Nullable<bool> red_status { get; set; }
        public Nullable<double> red_quantity { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Reward Reward { get; set; }
    }
}
