//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupTranGiaTichDiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_HistoryPointChange
    {
        public int his_id { get; set; }
        public string phone { get; set; }
        public string fullname { get; set; }
        public Nullable<System.DateTime> his_date { get; set; }
        public string his_note { get; set; }
        public Nullable<double> his_pointchange { get; set; }
        public int acc_id { get; set; }
    }
}
