//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupTranGiaTichDiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RedemptionDetails
    {
        public int redemption_id { get; set; }
        public string phone { get; set; }
        public string fullname { get; set; }
        public Nullable<double> points_required { get; set; }
        public string reward_name { get; set; }
        public Nullable<bool> red_status { get; set; }
    }
}
