//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupTranGiaTichDiem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class WishlistItem
    {
        public int WishlistItemId { get; set; }
        public Nullable<int> RewardId { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<int> AccId { get; set; }
        public Nullable<bool> status { get; set; }

        public virtual Account Account { get; set; }
        public virtual Reward Reward { get; set; }
        [NotMapped]
        public double TotalPoints
        {
            get { return (double)(Reward.points_required * Quantity); }
        }
    }
}
